### ISSUE TITLE
Problem rendering from widget state at notebook start

### ISSUE THREAD

**Issue by oscar6echo** [QuantStack/ipysheet#10]
I have found a strange edge case.
When I reopen a notebook containing widget state with a sheet, I see 2 headers and not small broken red link to indicate the widget is not connected to a kernel (as all core widget do).  

![screenshot-ipysheet-issue](https://user-images.githubusercontent.com/2219383/35772502-45a78550-0940-11e8-9a57-9011a5a573e2.png)

To reproduce:
+ Run this [sample notebook](https://github.com/oscar6echo/notebook-snapshot/blob/master/sample_notebook.ipynb).  
+ Save widget state
+ Reopen notebook

Note that it's only a rendering problem it seems as applying nbconvert (with a [template](https://github.com/oscar6echo/notebook-snapshot/blob/master/notebook_snapshot/templates/main.tpl.html) to work with ipywidgets 7.x) works fine.  

Also note the missing broken red link...

**Comment by maartenbreddels** [comment]
This is still a bug, just rendering the sheet and killing the kernel gives me this:

![image](https://user-images.githubusercontent.com/1765949/53889135-2c704180-4026-11e9-8932-cbfd416e04f4.png)

**Comment by maartenbreddels** [comment]
It seems handsontable *is* the widget div, and doesn't work nicely with the CSS that puts the disconnected icon there:
![image](https://user-images.githubusercontent.com/1765949/53889904-845b7800-4027-11e9-99bc-091d7afa3dac.png)

A possible workaround could be to place a div inside.
