### ISSUE TITLE
numeric parsing issues

### ISSUE THREAD

**Issue by krey** [QuantStack/ipysheet#102]
Follow up to https://github.com/QuantStack/ipysheet/issues/97
Using version https://github.com/QuantStack/ipysheet/commit/5065a5975c48ae56ef1d86c61e5174435f64cb0d

```python
import ipysheet

sheet = ipysheet.Sheet(rows=1, columns=1)
sheet.cells = ipysheet.Cell(value=None, row_start=0, row_end=0, column_start=0, column_end=0, type='numeric'),

sheet
```

Exhibit A:

1. Run code
2. Type "1" (sans quotes) into cell
3. Cell contains 1.000, right aligned
4. `sheet.cells[0].value == '1'` a string!

Exhibit B:

1. Run code
2. Type "1" (sans quotes) into cell
3. Cell contains 1.000, right aligned
4. Type "2" (sans quotes) into cell
5. Cell contains 2.000, right aligned
6. `sheet.cells[0].value == 2` an integer

Exhibit C:

1. Run code
2. Type "1" (sans quotes) into cell
3. Cell contains 1.000, right aligned
4. Type "2." (sans quotes) into cell
5. Cell contains 2., left aligned
6. `sheet.cells[0].value == '2.'` a string

Now change code to

```python
import ipysheet

sheet = ipysheet.Sheet(rows=1, columns=1)
sheet.cells = ipysheet.Cell(value="", row_start=0, row_end=0, column_start=0, column_end=0, type='numeric'),

sheet
```

Exhibit D:
1. Run new code
2. Type "1" (sans quotes) into cell
3. Cell contains 1.000, right aligned
4. `sheet.cells[0].value == 1` an integer

**Comment by martinRenou** [comment]
Thanks for taking the time for filling this issue...
I was expecting Handsontable cell validation to take care of those kinds of type validation but it looks like I was wrong.
@maartenbreddels shouldn't Handsontable validation logic take care of this? This is like completely broken, you cannot type a number into a `numeric` cell without it being turned into a string?

I guess the way to fix it would be to convert the cell value after cell change. But really, Handsontable should do it. This kind of logic should not live in ipysheet base code... Maybe I'm wrong and it is only a parameter to change in Handsontable?

**Comment by martinRenou** [comment]
Note: Setting the [allowInvalid](https://handsontable.com/docs/6.2.2/Options.html#allowInvalid) parameter to false does not fix those use cases. At least it prevents the user to type something like "Hello" in a numeric cell.

**Comment by martinRenou** [comment]
This is a bug from Handsontable. When editing a numeric cell, the new value should be cast to number.

**Comment by martinRenou** [comment]
I was wrong. Handsontable receives a string but correctly parses the numeric value for numeric cells. The issue is actually that when having a `None` value in the cell, the cell metadata (type, style etc) is not set. Resulting in having a default `text` cell. I'll open a PR with a fix.

Concerning the other code example you gave
```python
import ipysheet

sheet = ipysheet.Sheet(rows=1, columns=1)
sheet.cells = ipysheet.Cell(value="", row_start=0, row_end=0, column_start=0, column_end=0, type='numeric'),

sheet
```
I think we should not fix it. You are passing a string to a numeric cell. IMO this piece of code should throw Python side.
