### ISSUE TITLE
Support for Google Colab Notebooks

### ISSUE THREAD

**Issue by vasim07** [QuantStack/ipysheet#111]
```
!pip install ipysheet
!jupyter nbextension enable --py widgetsnbextension --sys-prefix

import ipysheet
sheet = ipysheet.sheet()
display(sheet)
```
The above code does not display anything in Google colab notebooks.

[Google colab Link](https://colab.research.google.com/drive/1DyQpCoXOS2cz32MahsmP_3NG6suU1_eL)

**Comment by martinRenou** [comment]
Google Colab is on its way to support interactive widgets https://github.com/googlecolab/colabtools/issues/60. I guess you would still need to wait a bit for an ipysheet support in Colab.
