### ISSUE TITLE
to_dataframe() Feature request

### ISSUE THREAD

**Issue by whugarra** [QuantStack/ipysheet#112]
After I write data into the table widget, I want to use to_dataframe() to get the new table, but it does not seems to have such a feature Currently.

**Comment by martinRenou** [comment]
You have an example using `to_dataframe` here: https://github.com/QuantStack/ipysheet/blob/master/examples/pandas.ipynb

**Comment by whugarra** [comment]
I means that if it possible to get the table like that?
![image](https://user-images.githubusercontent.com/30500088/56640219-0883c080-66a5-11e9-8a0c-2cdfd64e3494.png)

**Comment by whugarra** [comment]
@martinRenou

**Comment by martinRenou** [comment]
Oups, that's a bug actually. I'll take a look at it

**Comment by martinRenou** [comment]
thanks for reporting!

**Comment by martinRenou** [comment]
Wait, actually you did not define any cell, which means that there is no synchronization between the backend and the frontend.
If you try this:
```python
from ipysheet import sheet, column, to_dataframe

s = sheet()
column(0, [0, 0, 0, 0, 0])
s

to_dataframe(s)
```
You will see that you can edit the first column and export again to a Pandas dataframe.

Actually you pointed out a missing feature concerning cell edit. When you set a value by hand in a sheet cell that is not linked to a `Cell` widget, we should create it. That should fix your initial issue.

**Comment by whugarra** [comment]
it‘s works! thanks a lot~

**Comment by Maxust** [comment]
@martinRenou, hi mate!

can you have a look at two things please?

1) get an error here: 

`d = {'col1': [2,8], 'col2': [3,6]}
df = pd.DataFrame(data=d)
sheet2 = ipysheet.sheet(rows=3 , columns=3, column_headers=False, row_headers = False) 
column =  ipysheet.column(0, value = df.columns.to_list(), row_start = 1) 
cell_value = ipysheet.cell(0, 0, 'Attribute')
cell_value1 = ipysheet.cell(0, 1, 'Format')
cell_value2 = ipysheet.cell(0, 2, 'Description')
sheet2`

`ipysheet.to_dataframe(sheet2)`

what I get:

![image](https://user-images.githubusercontent.com/40881247/99428322-89ee1400-2917-11eb-9d86-20a2687c2188.png)

2) I worked with a simple example of a sheet, made an interaction change in of the cells and then used ipysheet.to_dataframe(sheet_name). It transformed to pd.DataFrame but regardless of the change was done (just original sheet was transformed to dataframe). It does not have to save such changes? 

Thank you ahead.
