### ISSUE TITLE
cell(type='time') feature request

### ISSUE THREAD

**Issue by tjangoW** [QuantStack/ipysheet#115]
Hi,
For my usage (and possibly someone else's), it would probably be great to have `time` cell support, which seems to be available at Handsontable already.

**Comment by martinRenou** [comment]
I can add it, please keep in mind that we might replace Handsontable by another JS library at some point. We will try our best keeping the same features, but some things will change.

**Comment by martinRenou** [comment]
This should be fixed by #117
