### ISSUE TITLE
Sheet.observe is not doing anything

### ISSUE THREAD

**Issue by chaffra** [QuantStack/ipysheet#12]
Hello,
It seems Sheet.observe is not working. I am trying to trigger an event when any cell in the sheet changes. here is an example below. Changing a or b does not update the sum.

```
import ipywidgets as widgets
sheet = ipysheet.sheet(rows=3, columns=2, column_headers=False, row_headers=False)
cell_a = ipysheet.cell(0, 1, 1, label_left='a')
cell_b = ipysheet.cell(1, 1, 2, label_left='b')
cell_sum = ipysheet.cell(2, 1, 3, label_left='sum', read_only=True)

# changes in a or b should trigger this function
def calculate(change):
    cell_sum.value = cell_a.value + cell_b.value

sheet.observe(calculate, type='All')
#cell_a.observe(calculate, 'value')
#cell_b.observe(calculate, 'value')
sheet
```

**Comment by krey** [comment]
1) You realize calculate would be called even when the sum changed (so twice every time)
2) `Sheet.observe` is only able to observe traits of the `Sheet` class. To get a list of these, run `sheet.trait_names()`
3) Maybe observing a `cell_range` is what you're looking for

**Comment by maartenbreddels** [comment]
> sheet.observe(calculate, type='All')

This will never be triggered since nothing in the sheet itself would change (the widget model), only the cells. The proper way is to listen to the cells (uncommenting the other observe lines would do it, or see this [example](https://ipysheet.readthedocs.io/en/latest/#Calculations)

**Comment by jmg421** [comment]
`sheet.trait_names()` returns:

`['_display_callbacks',
 '_dom_classes',
 '_model_module',
 '_model_module_version',
 '_model_name',
 '_msg_callbacks',
 '_property_lock',
 '_states_to_send',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'cells',
 'column_headers',
 'column_resizing',
 'column_width',
 'columns',
 'comm',
 'keys',
 'layout',
 'log',
 'named_cells',
 'row_headers',
 'row_resizing',
 'rows',
 'search_token',
 'stretch_headers']`
