### ISSUE TITLE
Add vertical scrollpane/bar to sheet

### ISSUE THREAD

**Issue by willferreira** [QuantStack/ipysheet#135]
Is it possible to add a vertical scroll pane to a sheet? Currently I'm limited to the scrolling provided by the browser, but for a large sheet this is going to be inadequate.

**Comment by SylvainCorlay** [comment]
Hey @willferreira, thanks for posting.

By default, ipysheet will take as much vertical space as needed to display all the rows. One way to get scrollbars is to manually set the height:

```
sheet.layout.height = '300px'
```

and then scrollbars will appear if the set height cannot accommodate all the rows.
