### ISSUE TITLE
"Error displaying widget" error after install

### ISSUE THREAD

**Issue by gunstonej** [QuantStack/ipysheet#141]
hi there, 

I've run the following commands from the ipysheet Github main page:
https://github.com/QuantStack/ipysheet
`conda install -c conda-forge ipysheet`
`jupyter labextension install ipysheet`

And i get an "Error displaying widget" error when i run the example notebooks within the ipysheet repo:
![image](https://user-images.githubusercontent.com/21370980/61589323-3a22ff80-aba0-11e9-834b-4e7d094f2673.png)

My environment is as follows:
![image](https://user-images.githubusercontent.com/21370980/61589403-4cea0400-aba1-11e9-9e66-65a3db0383d1.png)

I've also tried running:
`jupyter lab build`

and restarting the kernel etc.

have i missed something / any suggestions? 

Cheers,

**Comment by martinRenou** [comment]
There is one command missing to make it work:
```
jupyter labextension @jupyter-widgets/jupyterlab-manager
```

**Comment by martinRenou** [comment]
Sorry I went a bit fast looking at your issue. It seems like your version of JupyterLab is outdated. Would you mind trying to update JupyterLab?

**Comment by gunstonej** [comment]
sorry for the delay. i've updated my JupyterLab and it is now working as expected. 
many thanks
