### ISSUE TITLE
cell_range of text cells: all texts get shortened to their first character

### ISSUE THREAD

**Issue by roerd** [QuantStack/ipysheet#144]
### Reproducing the problem

* Create an array of string:
  ```
  arr = np.empty((3,4), str)
  arr.fill("foo")
  ```

* Create a Sheet with a cell_range spanning the whole array:
  * either with the numpy_loader
    ```
    ipysheet.from_array(arr)
    ```
  * or manually
    ```
    s = ipysheet.sheet(rows=3, columns=4)
    ipysheet.cell_range(arr)
    s
    ```

In both cases, the entries get shortened to just "f". Any new values entered into the cells will also be shortened to their first character.

**Comment by roerd** [comment]
Oops, I just noticed that the cause of this problem was because numpy uses strings of a fixed length and defaults to 1. So it's not an ipysheet problem, sorry.

**Comment by martinRenou** [comment]
Happy you found your issue :)
