### ISSUE TITLE
Issue about update cell's attribute without construct a new one.

### ISSUE THREAD

**Issue by ke-zhang-rd** [QuantStack/ipysheet#146]
My code here
```
import ipysheet
mysheet = ipysheet.sheet(rows=2, columns=2)
mysheet
c = cell(0,0,1, background_color = 'red')
```
I want to change `background_color`, I expect to do something like this
```
c.background_color = 'yellow'
```
Or later
```
mysheet[0, 0].background_color = 'yellow'
```
instead of this
```
c = cell(c.row_start, c.column_start, c.value, background_color = 'yellow')
```

Excuse me if I make a _read-doc-for-me_ issue. But I didn't find method I expect. If there isn't, could anyone explain? Thanks

**Comment by martinRenou** [comment]
No need to apologies, I agree this is super confusing

The helper `cell` function for creating the `Cell` object takes a `background_color` argument **but** the `Cell` class has no `background_color` attribute...

Instead, there is the `style` attribute that you can change. So you can do:
```python
import ipysheet
mysheet = ipysheet.sheet(rows=2, columns=2)
display(mysheet)

c = ipysheet.cell(0, 0,1, background_color = 'red')

# And later on
c.style = {'backgroundColor': 'yellow'}
```

I would suggest not using the helper functions and directly instantiate the `Sheet` and the `Cell` objects, adding the cell to the sheet manually with `mysheet.cells = [c]`. That is more complicated but also more explicit.

**Comment by ke-zhang-rd** [comment]
Thanks for your response. I think I tried use `style` to access `backgroundColor` before, but in a wrong way. 
I did `c.style['backgroundColor'] = 'yellow'` instead of `c.style = {'backgroundColor': 'yellow'}`. After read some `ipywidget` code, looks later approach will trigger [add_traits](https://github.com/jupyter-widgets/ipywidgets/blob/f8cad9dceeef1f911da66c995a3877ffe964e6c0/ipywidgets/widgets/widget.py#L594) which tigger [send_state](https://github.com/jupyter-widgets/ipywidgets/blob/f8cad9dceeef1f911da66c995a3877ffe964e6c0/ipywidgets/widgets/widget.py#L594) which make front-end update. Could you confirm that?

**Comment by martinRenou** [comment]
Yes, that's exactly it. Ipywidgets uses traitlets internally, and traitlets
does not observe internal changes on list/dict elements. It only observes
attribute assignements on `HasTraits` instances.
