### ISSUE TITLE
"Error Displaying Widget"

### ISSUE THREAD

**Issue by JohnOmernik** [QuantStack/ipysheet#147]
I realize there is a closed issue on this, however mine is a bit different, as of now, another bug is keeping me from upgrading.  I don't think the answer should be "just upgrade" here's my environment. 

 jomernik@3b5ee916be7d:/opt/conda/bin$ conda list ipysheet
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
ipysheet                  0.4.3                      py_0    conda-forge
jomernik@3b5ee916be7d:/opt/conda/bin$ conda list ipywidgets
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
ipywidgets                7.5.1                      py_0    conda-forge
jomernik@3b5ee916be7d:/opt/conda/bin$ jupyter lab --version
0.35.6
jomernik@3b5ee916be7d:/opt/conda/bin$ jupyter labextension list
JupyterLab v0.35.6
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @ijmbarr/jupyterlab_spellchecker v0.1.4  enabled  OK
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        @jupyterlab/hub-extension v0.12.0  enabled  OK
        @jupyterlab/plotly-extension v1.0.0  enabled  OK
        beakerx-jupyterlab v1.4.1  enabled  OK
        ipysheet v0.4.3  enabled  OK
        jupyterlab_bokeh v0.6.3  enabled  OK
jomernik@3b5ee916be7d:/opt/conda/bin$

**Comment by martinRenou** [comment]
You need to upgrade your JupyterLab, it should be `>=1.0`

**Comment by JohnOmernik** [comment]
As I stated, I connect due to a bug in a different package I am waiting on.  Did this not work with ANY version prior to 1.0?  Are any of the previous releases acceptable with this version?

**Comment by martinRenou** [comment]
You should then downgrade ipywidgets, at least `<=7.4`. And you should downgrade ipysheet, at least `<=0.4.2`

**Comment by martinRenou** [comment]
And because you are using Jupyter lab you would also need to downgrade the labextension... I don't know which version for `@jupyter-widgets/jupyterlab-manager`, but you need `<=0.4.2` for the ipysheet labextension
