### ISSUE TITLE
Please release & publish new version to support JLab 2

### ISSUE THREAD

**Issue by motcke** [QuantStack/ipysheet#157]
Hi, 

I see that there's already a new commit https://github.com/QuantStack/ipysheet/commit/187bacc59edb201f19c182e35ab096bb766597f3 from a few weeks ago to support JupiterLab 2, but the latest release is almost 10 months old now!

For now, I'm not able to use the library with JupyterLab 2 (fails with `Error displaying widget: model not found` because of versioning). 
Can you please release a new version?

Thanks.

**Comment by ofirbit** [comment]
Hey, any updates with the Jupyter 2 release?

**Comment by martinRenou** [comment]
I think there is an issue with the current update. We need to fix it before making a release.

**Comment by motcke** [comment]
Any estimation on when it will be fixed?

**Comment by martinRenou** [comment]
Release done! Available through pip for now. Soon on conda.

You should technically already be able to have something working on JupyterLab 2 by doing 
```
jupyter labextension install ipysheet@latest
```
without updating the Python package.

**Comment by motcke** [comment]
Many thanks
