### ISSUE TITLE
Widget does not display

### ISSUE THREAD

**Issue by ghost** [QuantStack/ipysheet#172]
### Environment
Operating System: Ubuntu version 18.04.4
Python Version: Python 3.7.8
How did you install ipysheet: conda
Python packages: 
[py37_rdkit.txt](https://github.com/QuantStack/ipysheet/files/5045886/py37_rdkit.txt)

### Description of Issue
I don't seem to be able to display any widget. How should I solve it?
Thank you!
![Screenshot from 2020-08-08 19-33-37](https://user-images.githubusercontent.com/67099904/89716586-7fce8800-d9ae-11ea-801d-235f493b8a6d.png)

**Comment by ArnaudHemmerle** [comment]
I have exactly the same issue, could you tell me if a solution was found?

**Comment by xiaoyangegege** [comment]
maybe you need to install the ipysheet first and enable the widget to jupyter notebook using following cmd:
jupyter nbextension enable --py --sys-prefix ipysheet

**Comment by martinRenou** [comment]
Will be fixed by https://github.com/QuantStack/ipysheet/pull/200
