### ISSUE TITLE
Ipysheet jupyterlab extension does not work in jupyterlab 3.0.1

### ISSUE THREAD

**Issue by mironvanderkolk** [QuantStack/ipysheet#184]
Tried installing in a fresh environment via:
```
pip install jupyterlab==3.0.1
pip install ipysheet==0.4.4
jupyter-labextension install @jupyter-widgets/jupyterlab-manager
jupyter-labextension install ipysheet@0.4.4
```
will result in 
`semver range ^0.4.4 is not registered as a widget module`

error when trying
```
import ipysheet
ipysheet.sheet()
``` 
in an empty notebook.

Pip freeze output:
```
anyio==2.0.2
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
bleach==3.2.1
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
idna==2.10
ipykernel==5.4.2
ipysheet==0.4.3
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.6.2
jedi==0.18.0
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-core==4.7.0
jupyter-server==1.1.4
jupyterlab==3.0.1
jupyterlab-pygments==0.1.2
jupyterlab-server==2.0.0
jupyterlab-widgets==1.0.0
MarkupSafe==1.1.1
mistune==0.8.4
nbclassic==0.2.5
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nest-asyncio==1.4.3
notebook==6.1.6
packaging==20.8
pandocfilters==1.4.3
parso==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.9.0
prompt-toolkit==3.0.9
ptyprocess==0.7.0
pycparser==2.20
Pygments==2.7.3
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2020.5
pyzmq==20.0.0
requests==2.25.1
Send2Trash==1.5.0
six==1.15.0
sniffio==1.2.0
terminado==0.9.2
testpath==0.4.4
tornado==6.1
traitlets==5.0.5
urllib3==1.26.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
```

jupyter-labextension list output
```
JupyterLab v3.0.1
/home/miron/.pyenv/versions/3.8.6/envs/deps-update-jan/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /home/miron/.pyenv/versions/3.8.6/envs/deps-update-jan/share/jupyter/lab
        ipysheet v0.4.4 enabled OK
```

**Comment by martinRenou** [comment]
Indeed ipysheet does not support JupyterLab 3. We'll try to make an update soonish, meanwhile, I can only suggest staying with JupyterLab 2.

**Comment by mironvanderkolk** [comment]
Okay, thanks for the quick response!

**Comment by sntgluca** [comment]
Hi all,
Just a quick check if there's a timeline for this ticket.
I just wish to remind that moving to Jupyterlab 3 is becoming increasingly interesting for most people, and the sooner this is done the better it would be for the users... :)
Thanks!

**Comment by JohnOmernik** [comment]
What's really strange here is when I run the jupyter/docker-stacks image with JupyterLab 3.0.14 (I built up to the scipy-notebook) and then added ipysheets and the extension, it installed as the following:

```
JupyterLab v3.0.14
/opt/conda/share/jupyter/labextensions
        jupyter-matplotlib v0.9.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        @j123npm/qgrid2 v1.1.4 enabled OK
        ipysheet v0.4.4 enabled OK
        jupyterlab-plotly v4.14.3 enabled OK
        plotlywidget v4.14.3 enabled OK
```
And it works just great.  When I try to run the exact commands in a conda environment in Windows, then it fails.  (With the semver error above) I do have to use --dev-build=True on the Dockerside but than it works fine in the Docker container... 

I am thinking it may be windows thing? That's really odd to me, is it just a check it throws to see if it SHOULD run? Why wouldn't the Docker Container be tripping that check as well?

**Comment by LukaPitamic** [comment]
Any news?

**Comment by LukaPitamic** [comment]
@maartenbreddels, 
installation of this extension on JL3 brakes all other already installed extensions. 
I spent whole day trying to figure out why everything brakes when trying to setup my stack on JLv3.
While banging my head against the wall :) - I stumbled upon:
https://gitlab.com/DGothrek/ipyaggrid/-/issues/37
(read the bottom comment from repo maintainer)

**Comment by martinRenou** [comment]
Will be fixed by https://github.com/QuantStack/ipysheet/pull/200
