### ISSUE TITLE
/dist AMD modules not published

### ISSUE THREAD

**Issue by jasongrout-db** [QuantStack/ipysheet#230]
Looking at https://www.jsdelivr.com/package/npm/ipysheet, it appears that the dist/ directory with AMD modules is not being published with the package, which means that the html manager (and currently Voila?) cannot use ipysheet by loading it from CDN. I think this also may affect using it in Colab and Databricks, and maybe VS Code as well?

Fixing this may be as simple as adding the dist/ directory to the package.json `files` field: https://github.com/QuantStack/ipysheet/blob/master/package.json#L19

**Comment by jasongrout** [comment]
I put in a PR for this change at https://github.com/QuantStack/ipysheet/pull/232

**Comment by jasongrout-db** [comment]
Thanks @martinRenou. Do you have a timeline for when a new npm package might be published that includes this dist directory?

**Comment by mrileysamc** [comment]
It's working!!!! Thank you @martinRenou  and @jasongrout !
