### ISSUE TITLE
Incompatability with ipywidgets 8.x

### ISSUE THREAD

**Issue by oruebel** [QuantStack/ipysheet#231]
It looks like in 8.0 ipywidgets removed the ``register(name=...)`` signature for the decorator and instead requires the use of ``register(widget=...)`` signature. This causes the following (and probably other) calls to ``register`` to fail in ipysheet when used with ipywidgets 8.x:

https://github.com/QuantStack/ipysheet/blob/89a80c4299f15810d665b9a4d68f18739c66c339/ipysheet/sheet.py#L14
https://github.com/QuantStack/ipysheet/blob/89a80c4299f15810d665b9a4d68f18739c66c339/ipysheet/sheet.py#L78
https://github.com/QuantStack/ipysheet/blob/89a80c4299f15810d665b9a4d68f18739c66c339/ipysheet/sheet.py#L83

Here the relevant PR on ipywidgets that removed this functionality https://github.com/jupyter-widgets/ipywidgets/pull/2695 and here the link to 8.0 release notes https://github.com/jupyter-widgets/ipywidgets/releases/tag/8.0.0

This issue was originally reported by @anhknguyen96 in https://github.com/NeurodataWithoutBorders/nwbwidgets/issues/220

**Comment by alexandreCameron** [comment]
I'm trying to bump the version of ipywidget on my repo but the incompatibility blocs this upgrade.

I'd be really thankful if PR could change the install required by ipysheet:

https://github.com/QuantStack/ipysheet/blob/master/setup.py#L70
