### ISSUE TITLE
Support for JupyterLite

### ISSUE THREAD

**Issue by giswqs** [QuantStack/ipysheet#239]
It would be great if ipysheet can support JupyterLite. It appears that the `jupyter_server` dependency is causing issues. Is it possible to make it an optional dependency? Otherwise, all downstream packages of ipysheet can't support JupyterLite. 

https://github.com/giswqs/leafmap/issues/55

![image](https://user-images.githubusercontent.com/5016453/203799429-cc698480-f370-4da7-8300-50af34dff097.png)
![image](https://user-images.githubusercontent.com/5016453/203799530-db87b9f0-eb05-4d3b-98fd-771f1182c7eb.png)

**Comment by martinRenou** [comment]
I believe ipysheet actually does not depend on `jupyter_server`, I don't know why it's listed there but it might be a leftover.
