### ISSUE TITLE
checkbox value not updating

### ISSUE THREAD

**Issue by krey** [QuantStack/ipysheet#29]
```python
import ipysheet

kwargs = dict(row_start=0, row_end=0, squeeze_column=True, squeeze_row=True)

grid = ipysheet.Sheet(rows=1, columns=2, column_headers = False, row_headers=False, column_width=[20, 100])
grid.cells = (ipysheet.Cell(value=True, column_start=0, column_end=0, type='checkbox', **kwargs),
              ipysheet.Cell(value='True', column_start=1, column_end=1, **kwargs))

grid.cells[0].value = False
grid.cells[1].value = 'False'

grid
```
This shows a checked box and a cell containing "False"

Somewhat related to https://github.com/QuantStack/ipysheet/issues/3

**Comment by martinRenou** [comment]
I am not able to reproduce your issue. I'm using `master`. Maybe it was fixed since the last version. Did you try using `master`?

![checked](https://user-images.githubusercontent.com/21197331/53086070-a7a10600-3504-11e9-8831-d5f977d773c0.png)

**Comment by krey** [comment]
My bad, thank you
