### ISSUE TITLE
Widget cell type

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/ipysheet#31]
It would be nice to be able to put a widget in a cell. It is possible to [create a cutsom cell type](https://handsontable.com/docs/6.2.2/tutorial-cell-types.html), maybe that feature will be helpful.

**Comment by nickpollari** [comment]
This would definitely be helpful. It is common to use a button or something else on row indices to remove rows which are no longer needed.

**Comment by martinRenou** [comment]
There is a PR opened #43 for a first simple version of a Widget cell. In the current version of the PR, the cell value IS a widget, and we create a view for this widget in the cell renderer.
Some ideas of improvement:
- The value of the cell should not be an actual widget
- The visual representation of the cell is a widget, specified with a cell option. e.g `cell(0, 0, 0.5, options={'renderer': FloatSlider(...)})` and this option is used in the renderer for creating the widget view. The value of the cell is automatically bound to the widget.
- An other option for the user could be an editor widget. e.g. `cell(0, 0, 0.5, options={'editor': FloatSlider(...)})`. In this case the cell value would be rendered normally, but when the user clicks on the cell for editing it, a view of the widget is displayed.
- If the user gives a `ValueWidget` for the cell value, we use the value of the widget for the cell value, and the widget itself for the renderer.

**Comment by martinRenou** [comment]
@maartenbreddels We need a way to create a range of cells with widget renderers.
```python
ipysheet.column(0, [0.] * 5, renderer=FloatSlider(...))
```
Does not work, because there cannot be one slider renderer for 5 elements.

I'm thinking there should be a `renderers` parameter which has the same shape as `value`, containing renderer names and widgets. What do you think?

**Comment by maartenbreddels** [comment]
I think we should just not support that FTM, only a single cell value.

**Comment by martinRenou** [comment]
But I mean, in a near future, that would be the way to go, right?

**Comment by maartenbreddels** [comment]
I think we can consider this closed right? Since 0.3 we support this.

PS: we have inconsistent tagging btw, no v prefix

**Comment by martinRenou** [comment]
Yes, we can close it :)

Oh, apparently. We usually don't use a "v" prefix in our packages. Is it reversible?

**Comment by maartenbreddels** [comment]
I find it easier to separate them from other tags, `git checkout v<tab completion>`
Better just retag that with v0.3.0 as well?
