### ISSUE TITLE
Cell checkbox value not converted to Python bool

### ISSUE THREAD

**Issue by oscar6echo** [QuantStack/ipysheet#4]
While arguable this is what you'd expect.  
It gets converted to text 'true' or 'false' and appear as 1 or 0 in a `on_value_change(change)` context.
See 'basics' nb in  [ipysheet-demo](https://github.com/oscar6echo/ipysheet-demo) repo for the first remark and 'demo_ipysheet_bs' for the second.

Could it be done in a natural way ?

**Comment by maartenbreddels** [comment]
Bool was not an allowed type, it was typecast to string or float, it now is.
