### ISSUE TITLE
slider in cell not updating

### ISSUE THREAD

**Issue by jasongrout** [QuantStack/ipysheet#56]
Congrats on a release! I'm using the binder at https://mybinder.org/v2/gh/QuantStack/ipysheet/stable?filepath=examples.

I notice that when I run the first two cells of widget_cell notebook, a couple of things happen:

(a) the widget in the ipysheet cell resizes as I change it's value.
(b) When I move the slider in the first notebook cell (outside of ipysheet), the slider in ipysheet doesn't update, but the value in ipysheet does update.

![screenshot](https://user-images.githubusercontent.com/192614/53671631-29dfa780-3c34-11e9-8436-8acd8165c27b.gif)

**Comment by martinRenou** [comment]
Thanks for the report Jason :) The resize is due to the other cell value at C4. Concerning the synchronization update, I was sure this one was fixed... I'll try and fix it on Monday

**Comment by martinRenou** [comment]
This does not make sense to me... I added a test for it on Friday, the CI should not pass on master.
