### ISSUE TITLE
ipysheet hides error

### ISSUE THREAD

**Issue by krey** [QuantStack/ipysheet#69]
This isn't really a bug, just pointing out some unexpected behaviour compared to ipywidgets:

```python
import ipywidgets as widgets
import ipysheet

sheet = ipysheet.Sheet(rows=1, columns=1)
sheet.cells = ipysheet.Cell(row_start=0, row_end=0, column_start=0, column_end=0),
field = widgets.Text(continuous_update=False)

def update(change):
    raise RuntimeError
            
field.observe(update, names='value')
sheet.cells[0].observe(update, names='value')
```

If I type into `field` it shows the `RuntimeError` directly below the widget. If I type into `sheet`, the `RuntimeError` is not shown. Using an `Output` widget as a workaround.

**Comment by martinRenou** [comment]
The thing is that the error happens in a callback that is called when a cell value has changed, the sheet has nothing to do with it. 
Also, depending on whether you are using JupyterLab or the Jupyter Notebook I think the behavior can be different. This is not really related to ipysheet, but more to the Python kernel and the client (Jupyter Notebook, JupyterLab or even the console), it's the Python kernel that decides under which cell to send the standard output stream and error stream, and the client will decide where to put it.

I know this can be inconvenient when working... The only thing I can say is that your workaround could be actually the best way to fix it, it redirects everything to the widget.

If you don't mind I'll close this issue as it is not really related to ipysheet.

**Comment by krey** [comment]
Thanks @martinRenou.
You're right; in my JupyterLab, neither error is shown (original report was using Jupyter Notebook).
Quite a mess...

**Comment by martinRenou** [comment]
> Quite a mess...

I do agree with you :smile:. But if you think about it, the answer to the question `Where should I put the error stream?` might not be obvious. Say the sheet produces an error but you displayed two views of this sheet, under which view should we put the error stream? Maybe both, but if the error stack is really long you can end up with a big mess in the notebook. I might be wrong but I think the default behavior is to put it under the last view.
The thing is that Jupyter developers chose to put error streams and standard outputs under code cells. Usually, an IDE would put it in a console, in an other pane, next to the text editor. In that case there is only one place for output streams.
