### ISSUE TITLE
from_dataframe can't load columns with NaT fields

### ISSUE THREAD

**Issue by NickRuiz** [QuantStack/ipysheet#74]
I have a Pandas dataframe that has some `NaT` values in a column with datatype `datetime`, which were set using `pd.to_datetime()`. The current version of `from_datetime()` throws the following error when trying to load:

`ValueError: NaTType does not support strftime`

**Comment by martinRenou** [comment]
Thanks for the report! I'll try and fix it. Missing data are not well handled yet.

What do you think would be the best way of handling `NaT` values? Should it be an empty cell?
