### ISSUE TITLE
labextension missing the sub-command install in readthedocs

### ISSUE THREAD

**Issue by davecoutts** [QuantStack/ipysheet#76]
In the 'To make it work for Jupyter lab' section of https://ipysheet.readthedocs.io/en/latest/ the command 

```shell
jupyter labextension ipysheet
```
rather than
```shell
jupyter labextension install ipysheet
```
is shown.

Please add the install sub-command.

**Comment by martinRenou** [comment]
Thanks for the report :) It's a typo. If you would like to contribute and fix it, that would help a lot :)
