### ISSUE TITLE
Pandas int dtype is displayed as float

### ISSUE THREAD

**Issue by Braintelligence** [QuantStack/ipysheet#89]
When creating a sheet from_dataframe containing int dtypes these numbers are displayed as float in the resulting sheet.

**Comment by martinRenou** [comment]
Yeah that's because there is no such thing as integers in JavaScript... We can fix it by formatting changing the cell `numeric_format` if `dtype` is int. Thanks for the report! I'll fix it

**Comment by Braintelligence** [comment]
Watch out for variants of it, like `int64`, though 👍.

**Comment by martinRenou** [comment]
I will :) thanks
