### ISSUE TITLE
filling up an empty sheet in widget view

### ISSUE THREAD

**Issue by gburgunder** [QuantStack/ipysheet#93]
Hello, 
 I created an empty sheet in jupyterlab that I would like to fill up in the display view (I'm not sure I am using the right terminology).
Typically, I would add measurement values.
But when I try to extract these data, the sheet remains empty.
### to create  the sheet
sheet = ipysheet.sheet(rows=3, columns=2)
sheet
### to read it
a=ipysheet.to_array(sheet)

What I would like to do is to plot the two columns with pyplot.
Thanks!
![tmp](https://user-images.githubusercontent.com/14946115/54449352-2a0c9680-474e-11e9-9bb1-a4006a24848b.png)

**Comment by krey** [comment]
Probably easiest to set it up using `from_array`

```python
sheet = ipysheet.from_array(np.zeros((3, 2)))
```

Then edit and then call `ipysheet.to_array(sheet)`

**Comment by gburgunder** [comment]
Thanks!

**Comment by martinRenou** [comment]
Closing it. Feel free to reopen if you did not fix your issue @gburgunder
