### ISSUE TITLE
period terminated integer not recognized as numeric

### ISSUE THREAD

**Issue by krey** [QuantStack/ipysheet#97]
Version: https://github.com/QuantStack/ipysheet/commit/e285b95c689774cbd2459317d3fb61e44a86c553

![2019-03-22-070135](https://user-images.githubusercontent.com/223908/54818769-679e8180-4c70-11e9-8a08-491bd4128795.png)

Maybe this isn't a real bug, but when coding, it's common to write a floating point integer ending with a full stop, e.g. `100.` to be explicit about its type, or to deal with Python 2's default division, etc.

**Comment by martinRenou** [comment]
Mmh, just one thing first, why are you creating your cell like that:
```
Cell(value='', ..., type='numeric')
```
?
You're passing a string value but you expect type to be numeric, it's kind of weird no?
Maybe you would prefer to use the easy API:
```
from ipysheet import sheet, cell # Without the capital letters

s = sheet()
cell(0, 0, value=4.)
s
```

**Comment by martinRenou** [comment]
Thinking about it, I think your `Cell(value='', ..., type='numeric')` should throw an error Python side

**Comment by krey** [comment]
> Thinking about it, I think your `Cell(value='', ..., type='numeric')` should throw an error Python side

So perhaps I should switch back to strings if I want to allow empty cells

**Comment by krey** [comment]
> Mmh, just one thing first, why are you creating your cell like that:
> 
> ```
> Cell(value='', ..., type='numeric')
> ```
> ?
> You're passing a string value but you expect type to be numeric, it's kind of weird no?
> Maybe you would prefer to use the easy API:
> 
> ```python
> from ipysheet import sheet, cell # Without the capital letters
> 
> s = sheet()
> cell(0, 0, value=4.)
> s
> ```

Thanks Martin.

I'm familiar with the "easy" API, but I'm opposed to its matplotlib style "everything is a side-effect" philosophy.

**Comment by martinRenou** [comment]
I do agree with you concerning the matplotlib API, but we gotta admit that it is pretty useful.

Anyway, I don't really get what you mean by `"So perhaps I should switch back to strings if I want to allow empty cells"`. Cells will be empty if values are None, if that's what you are looking for:
```python
s = ipysheet.sheet(rows=1, columns=4)
row = ipysheet.row(0, [0, None, 2, 3])
s
```
and this is the output:
![row](https://user-images.githubusercontent.com/21197331/54831907-84ac7200-4cbb-11e9-8737-c4ea45b47f80.png)
This example is using the easy API but you can replicate the same behavior with `Cell`, using numeric type.

**Comment by krey** [comment]
@martinRenou This is a little misleading.

Using master

```python
import ipysheet

sheet = ipysheet.Sheet(rows=1, columns=2)
sheet.cells = ipysheet.Cell(value=[1., None], row_start=0, row_end=0, column_start=0, column_end=1,
    squeeze_column=False, type='numeric', numeric_format='0.00'),

sheet.cells[0].value = [None, None]
```

Shows

![2019-04-04-140040](https://user-images.githubusercontent.com/223908/55577662-14054c80-56e2-11e9-94a6-5b630dc56648.png)

So I'm not able to None out non-None values :(

**Comment by martinRenou** [comment]
Closing this one, feel free to open again if needed

**Comment by krey** [comment]
@martinRenou Why close it?

The original issue (period terminated integer) still persists in https://github.com/QuantStack/ipysheet/commit/5065a5975c48ae56ef1d86c61e5174435f64cb0d

**Comment by martinRenou** [comment]
I closed it because it was an issue in your code, no? You were creating a 'numeric' cell given a string value.

I guess the link you just gave is wrong? It is not related to this issue

**Comment by martinRenou** [comment]
Oh sorry, I get it.

Yeah, the issue you are talking about still stands. I guess [this issue](https://github.com/QuantStack/ipysheet/issues/92) you already opened is clearer. We need to have an 'int' and a 'float' cell type. This could fix your issue.
