### ISSUE TITLE
development installation failed

### ISSUE THREAD

**Issue by whugarra** [QuantStack/ipysheet#99]
C:\Users\weiwa\ipysheet\js>npm install .

> puppeteer@1.12.2 install C:\Users\weiwa\ipysheet\js\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r624492! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (C:\Users\weiwa\ipysheet\js\node_modules\puppeteer\lib\helper.js:108:27)
    at Object.<anonymous> (C:\Users\weiwa\ipysheet\js\node_modules\puppeteer\install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-typescript@3.0.13 requires a peer of karma@1 || 2 but none is installed. You must install peer dependencies yourself.
npm WARN karma-typescript@3.0.13 requires a peer of typescript@2 but none is installed. You must install peer dependencies yourself.
npm WARN karma-webpack@3.0.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ipysheet@0.3.3 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.12.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.12.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

At first it warning that the ipysheet.egg-info folder was missing. I went to pypi to download the file and overwrite it, then used the npm install. command, but the following error occurred.  Whether I am operating incorrectly？thanks.

**Comment by martinRenou** [comment]
I guess it was just a network issue. If you try again it should work.

**Comment by martinRenou** [comment]
> I went to pypi to download the file and overwrite it

I think you should not do this kind of thing, if there is a warning because a file is missing it's because something is wrong in our repository or in the way you tried to install ipysheet. Did you follow the dev installation instructions?
```
git clone https://github.com/QuantStack/ipysheet.git
cd ipysheet
pip install -e .
jupyter nbextension install --py --symlink --sys-prefix ipysheet
jupyter nbextension enable --py --sys-prefix ipysheet
jupyter nbextension enable --py --sys-prefix ipysheet.renderer_nbext
jupyter labextension link js
```

**Comment by garra2** [comment]
Yes, I followed the operation step by step.but the error still there.
I have installed nodejs and i can build the develop enviroment of  the ipytree.

C:\Users\wei.wang\ipysheet>pip install -e .
Obtaining file:///C:/Users/wei.wang/ipysheet
    Complete output from command python setup.py egg_info:
    setup.py entered
    $PATH=C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Java\jdk1.8.0_191\jre\bin;C:\Program Files\Java\jdk1.8.0_191\bin;C:\PATH;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Users\wei.wang\AppData\Local\Continuum\anaconda3;C:\Users\wei.wang\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:\Users\wei.wang\AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Users\wei.wang\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\wei.wang\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\wei.wang\AppData\Local\Microsoft\WindowsApps;C:\Users\wei.wang\AppData\Local\JetBrains\WebStorm 2018.3.5\bin;;C:\Users\wei.wang\AppData\Local\Programs\Git\cmd;C:\Users\wei.wang\AppData\Roaming\npm
    running egg_info
    running jsdeps
    `npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
    rebuilding js and css failed
    missing files: ['C:\\Users\\wei.wang\\ipysheet\\ipysheet\\static\\extension.js', 'C:\\Users\\wei.wang\\ipysheet\\ipysheet\\static\\index.js', 'C:\\Users\\wei.wang\\ipysheet\\ipysheet\\static\\extension-renderer.js', 'C:\\Users\\wei.wang\\ipysheet\\ipysheet\\static\\renderer.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\wei.wang\ipysheet\setup.py", line 177, in <module>
        setup(**setup_args)
      File "C:\Users\wei.wang\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\wei.wang\AppData\Local\Continuum\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\wei.wang\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\wei.wang\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\wei.wang\ipysheet\setup.py", line 45, in run
        raise e
      File "C:\Users\wei.wang\ipysheet\setup.py", line 38, in run
        self.distribution.run_command('jsdeps')
      File "C:\Users\wei.wang\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\wei.wang\ipysheet\setup.py", line 112, in run
        raise ValueError(msg)
    ValueError: Missing file: C:\Users\wei.wang\ipysheet\ipysheet\static\extension.js
    npm is required to build a development version of widgetsnbextension

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\wei.wang\ipysheet\

**Comment by martinRenou** [comment]
It seems you don't have npm installed. Are you in a conda environment? If so you can run `conda install -c conda-forge nodejs`.

**Comment by martinRenou** [comment]
But it's weird, if you could install `ipytree` in a development mode it means that you have npm somewhere...

**Comment by garra2** [comment]
Of course i have npm .if I copy the "static" folder and "egg_info" folder from pypi, the error will be zhe first one

**Comment by martinRenou** [comment]
There is an issue (and a possible fix) on `Puppeteer` repository related to the first error you gave: https://github.com/GoogleChrome/puppeteer/issues/2173#issuecomment-399745457.

**Comment by maartenbreddels** [comment]
I think I know what is going on, on windows there are some issues with finding npm, in ipyvolume the commit that fixed it is:
https://github.com/maartenbreddels/ipyvolume/commit/a434ce71135e95844b1169655fe1d873a2e857a8

I think this went upstream to the cookiecutter, but that was before ipysheet was created.

Either one of you want to try to fix this? @garra2 a PR from you would be welcome, then we know for sure that it will work.

**Comment by whugarra** [comment]
This method does not seem to work.The same error occurred. 
but when I copy the "static" folder and "egg_info" folder from pypi, the error will be disappear.The first error was caused by the network Really.

**Comment by martinRenou** [comment]
@whugarra did you fix your issue? Do you know what it was in the end?
